In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [9]:
user= pd.read_excel(r"C:\Users\RHEA TIWARI\Desktop\Sem 5\ML\user_df.xlsx")
item= pd.read_excel(r"C:\Users\RHEA TIWARI\Desktop\Sem 5\ML\item_df.xlsx")

In [10]:
user

,user_id,book_id,rating,fiction,adult,novels,contemporary,adult-fiction,fantasy,romance,...,american-lit,realistic,1001-books,chic-lit,classroom-library,1001,mystery-suspense-thriller,childrens-literature,modern,spirituality
0,2,9762.0,3.0,0.0,4.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,4.0
1,3,9014.0,5.0,1.0,1.0,1.00,1.00,1.0,1.00,0.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
2,4,3273.0,4.0,2.0,2.0,2.00,2.00,2.0,0.00,2.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
3,7,3489.0,3.5,4.0,4.0,2.75,2.75,2.0,1.25,0.0,...,0.0,0.0,1.25,0.0,0.0,1.25,0.0,0.0,2.0,0.0
4,9,8676.0,5.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28901,53419,7911.0,5.0,4.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,4.0,0.0,0.0
28902,53420,5581.5,3.0,3.5,3.5,1.50,2.00,3.5,0.00,0.0,...,1.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
28903,53422,7667.0,4.0,4.0,4.0,4.00,4.00,4.0,4.00,4.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
28904,53423,4984.0,5.0,5.0,5.0,5.00,5.00,5.0,0.00,0.0,...,5.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
28905,53424,4214.0,3.0,5.0,5.0,5.00,5.00,5.0,5.00,0.0,...,0.0,0.0,5.00,0.0,0.0,5.00,0.0,0.0,0.0,5.0

In [11]:
item

,1,1001,1001-books,2016-reads,20th-century,21st-century,action,action-adventure,adult,adult-fiction,...,war,women,ya,ya-books,ya-fantasy,ya-fiction,ya-lit,young-adult,young-adult-fiction,youth
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
1,0,0,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,1,1,1,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
9996,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,1,0,1,1,0
9998,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [12]:
print(user.shape)  # Shape of user dataframe
print(user.columns)  # Column names in user dataframe

print(item.shape)  # Shape of item dataframe
print(item.columns)  # Column names in item dataframe

(28906, 213)
Index(['user_id', 'book_id', 'rating', 'fiction', 'adult', 'novels',
       'contemporary', 'adult-fiction', 'fantasy', 'romance',
       ...
       'american-lit', 'realistic', '1001-books', 'chic-lit',
       'classroom-library', '1001', 'mystery-suspense-thriller',
       'childrens-literature', 'modern', 'spirituality'],
      dtype='object', length=213)
(10000, 210)
Index(['1', '1001', '1001-books', '2016-reads', '20th-century', '21st-century',
       'action', 'action-adventure', 'adult', 'adult-fiction',
       ...
       'war', 'women', 'ya', 'ya-books', 'ya-fantasy', 'ya-fiction', 'ya-lit',
       'young-adult', 'young-adult-fiction', 'youth'],
      dtype='object', length=210)

In [13]:
item

,1,1001,1001-books,2016-reads,20th-century,21st-century,action,action-adventure,adult,adult-fiction,...,war,women,ya,ya-books,ya-fantasy,ya-fiction,ya-lit,young-adult,young-adult-fiction,youth
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
1,0,0,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,1,1,1,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
9996,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,1,0,1,1,0
9998,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [15]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Drop any rows with missing data
user_df = user_df.dropna()
item_df = item_df.dropna()

# Split the user data into features and labels
user_features = user_df.drop(columns=['user_id', 'book_id', 'rating'])  # Feature columns for the users
user_ratings = user_df['rating']  # Ratings or labels

# For item data, drop unnecessary columns
item_features = item_df  # Assuming all are features in this case

# Normalize the features
scaler = StandardScaler()
user_features_scaled = scaler.fit_transform(user_features)
item_features_scaled = scaler.fit_transform(item_features)

# Define the dimensions for input features
num_user_features = user_features_scaled.shape[1]
num_item_features = item_features_scaled.shape[1]

# Define the user neural network
user_NN = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation='relu', input_shape=(num_user_features,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(32)
])

# Define the item neural network
item_NN = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation='relu', input_shape=(num_item_features,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(32)
])

# Inputs for both user and item models
input_user = tf.keras.layers.Input(shape=(num_user_features,))
input_item = tf.keras.layers.Input(shape=(num_item_features,))

# Get the output of both neural networks
vu = user_NN(input_user)
vm = item_NN(input_item)

# Normalize the outputs
vu_normalized = tf.linalg.l2_normalize(vu, axis=1)
vm_normalized = tf.linalg.l2_normalize(vm, axis=1)

# Compute the similarity (dot product)
similarity = tf.keras.layers.Dot(axes=1)([vu_normalized, vm_normalized])

# Create the model
model = tf.keras.Model(inputs=[input_user, input_item], outputs=similarity)

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Convert the features to numpy arrays for training
user_features_np = np.array(user_features_scaled)
item_features_np = np.array(item_features_scaled)
ratings_np = np.array(user_ratings)

# Split the data for training and testing
X_train_user, X_test_user, X_train_item, X_test_item, y_train, y_test = train_test_split(
    user_features_np, item_features_np, ratings_np, test_size=0.2, random_state=42)

# Train the model
history = model.fit([X_train_user, X_train_item], y_train, epochs=10, batch_size=32, validation_data=([X_test_user, X_test_item], y_test))

# Predict for some test samples
predictions = model.predict([X_test_user, X_test_item])

# Show the results
print(predictions)

ValueError: Found input variables with inconsistent numbers of samples: [28906, 10000, 28906]

In [16]:
print("User Features Shape:", user_features_np.shape)
print("Item Features Shape:", item_features_np.shape)
print("Ratings Shape:", ratings_np.shape)

User Features Shape: (28906, 210)
Item Features Shape: (10000, 210)
Ratings Shape: (28906,)

In [17]:
user_ids = user['user_id']
item_ids = user['book_id']
ratings = user['rating']

# Identify the common item IDs in both user ratings and item features
common_item_ids = item['book_id'].values  # Adjust based on actual column name in item DataFrame

# Filter user data to keep only ratings for items that exist in the item DataFrame
valid_indices = np.isin(item_ids, common_item_ids)

# Update user data based on valid indices
filtered_user_ids = user_ids[valid_indices]
filtered_item_ids = item_ids[valid_indices]
filtered_ratings = ratings[valid_indices]

# Convert filtered data to numpy arrays
user_features_np = np.array(filtered_user_ids)  # Replace with actual user feature extraction if needed
item_features_np = np.array(item[item['book_id'].isin(filtered_item_ids)])  # Ensure this matches shape
ratings_np = np.array(filtered_ratings)

# Print shapes after filtering
print("Filtered User Features Shape:", user_features_np.shape)
print("Filtered Item Features Shape:", item_features_np.shape)
print("Filtered Ratings Shape:", ratings_np.shape)

# Now, you can split the data
X_train_user, X_test_user, X_train_item, X_test_item, y_train, y_test = train_test_split(
    user_features_np, item_features_np, ratings_np, test_size=0.2, random_state=42
)

KeyError: 'book_id'

In [18]:
new_item=pd.read_excel(r"C:\Users\RHEA TIWARI\Desktop\Sem 5\ML\new_item.xlsx")

In [19]:
# Get the column names from both dataframes
new_item_columns = set(new_item.columns)
user_df_columns = set(user_df.columns)

# Find the common columns between the two dataframes
common_columns = new_item_columns.intersection(user_df_columns)

# Print the common columns
print(common_columns)

# Optionally, you can create a new dataframe with just the common columns
common_columns_df = new_item[list(common_columns)]
print(common_columns_df.head())

{'bookclub', 'mysteries', 'adventure', 'ya-fantasy', 'english', 'historical-fiction', 'crime', 'coming-of-age', 'biography', 'funny', 'magic', 'romance', 'mystery', 'horror', 'juvenile', 'fantasy-scifi', 'science-fiction-fantasy', 'children', 'childrens-books', 'general-fiction', 'favorite-authors', 'calibre', 'childhood', 'fantasy-sci-fi', 'england', 'general', 'speculative-fiction', 'humor', 'family', 'paranormal', 'children-s', 'thrillers', 'chick-lit', 'science', 'young-adult', 'love', 'crime-mystery', 'library-book', 'supernatural', 'science-fiction', 'contemporary-fiction', 'adult-fiction', 'all-time-favorites', 'young-adult-fiction', 'mystery-thriller', 'suspense-thriller', 'favorite-series', 'reread', 'read-in-english', 'ya', 'mystery-suspense', 'stand-alone', 'history', 'action-adventure', 'classic', 'sci-fi-fantasy', 'contemporary', 'usa', 'home-library', 'scifi', 'childrens', 'ya-fiction', 'part-of-a-series', 'friendship', 'teen', 'sci-fi', 'mystery-crime', 'war', 'american', 'fantasy', 'literature', 'adult', 'comedy', 'ya-books', 'nonfiction', 'kids', 'contemporary-romance', 'high-school', 'literary', 'historical', 'fiction', 'nook', 'urban-fantasy', 'children-s-books', 'women', 'action', 'school', 'on-kindle', 'humour', 'favorite', 'drama', 'realistic-fiction', 'non-fiction', 'philosophy', 'novels', 'kids-books', 'thriller', 'classics', 'literary-fiction', 'book_id', 'bookshelf', 'suspense', 'scifi-fantasy', 'british', 'my-favorites'}
   bookclub  mysteries  adventure  ya-fantasy  english  historical-fiction  \
0         0          0          1           1        1                   0
1         0          0          0           1        0                   0
2         0          0          1           1        1                   0
3         0          0          1           1        1                   0
4         0          0          1           1        1                   0

   crime  coming-of-age  biography  funny  ...  kids-books  thriller  \
0      0              1          0      0  ...           1         0
1      0              1          0      0  ...           1         0
2      0              0          0      0  ...           1         0
3      0              0          0      0  ...           1         0
4      0              1          0      0  ...           1         0

   classics  literary-fiction  book_id  bookshelf  suspense  scifi-fantasy  \
0         1                 0        1          1         0              1
1         0                 0        2          0         0              1
2         1                 0        3          1         0              1
3         1                 0        5          1         0              1
4         1                 0        6          1         0              1

   british  my-favorites
0        1             1
1        1             1
2        1             1
3        1             1
4        1             1

[5 rows x 105 columns]

In [20]:
new_item

,book_id,4-stars,5-stars,abandoned,action,action-adventure,adult,adult-fiction,adventure,all-time-favorites,...,want-to-read,war,wish-list,women,ya,ya-books,ya-fantasy,ya-fiction,young-adult,young-adult-fiction
0,1,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
1,2,0,0,0,1,0,0,0,0,1,...,0,0,0,0,1,1,1,1,1,1
2,3,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
3,5,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
4,6,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,31538647,1,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,1,0,1,0
9996,31845516,0,0,1,0,0,1,0,0,1,...,0,0,1,1,0,0,0,0,0,0
9997,32075671,0,1,0,0,0,0,0,0,1,...,0,0,1,0,1,1,0,1,1,1
9998,32848471,1,0,0,0,0,1,1,0,1,...,0,0,1,0,0,0,0,0,0,0
9999,33288638,1,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [21]:
user

,user_id,book_id,rating,fiction,adult,novels,contemporary,adult-fiction,fantasy,romance,...,american-lit,realistic,1001-books,chic-lit,classroom-library,1001,mystery-suspense-thriller,childrens-literature,modern,spirituality
0,2,9762.0,3.0,0.0,4.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,4.0
1,3,9014.0,5.0,1.0,1.0,1.00,1.00,1.0,1.00,0.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
2,4,3273.0,4.0,2.0,2.0,2.00,2.00,2.0,0.00,2.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
3,7,3489.0,3.5,4.0,4.0,2.75,2.75,2.0,1.25,0.0,...,0.0,0.0,1.25,0.0,0.0,1.25,0.0,0.0,2.0,0.0
4,9,8676.0,5.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28901,53419,7911.0,5.0,4.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,4.0,0.0,0.0
28902,53420,5581.5,3.0,3.5,3.5,1.50,2.00,3.5,0.00,0.0,...,1.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
28903,53422,7667.0,4.0,4.0,4.0,4.00,4.00,4.0,4.00,4.0,...,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
28904,53423,4984.0,5.0,5.0,5.0,5.00,5.00,5.0,0.00,0.0,...,5.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0
28905,53424,4214.0,3.0,5.0,5.0,5.00,5.00,5.0,5.00,0.0,...,0.0,0.0,5.00,0.0,0.0,5.00,0.0,0.0,0.0,5.0

In [22]:
import pandas as pd

# Assuming new_item and user are already loaded DataFrames

# Step 1: Select 'user_id' and 'rating' columns from the user DataFrame
user_columns = user[['book_id', 'user_id', 'rating']]

# Step 2: Merge new_item with user columns based on 'book_id'
combined_df = pd.merge(new_item, user_columns, on='book_id')

# Step 3: The resulting combined DataFrame will contain all columns from new_item plus 'user_id' and 'rating'
print(combined_df.head())

   book_id  4-stars  5-stars  abandoned  action  action-adventure  adult  \
0      105        0        0          0       0                 0      1
1      355        0        0          1       0                 0      0
2      415        0        0          1       0                 0      0
3      428        0        0          1       0                 0      1
4      449        0        0          1       0                 0      0

   adult-fiction  adventure  all-time-favorites  ...  wish-list  women  ya  \
0              1          1                   1  ...          0      0   0
1              0          1                   0  ...          0      0   0
2              0          0                   1  ...          1      0   0
3              1          0                   0  ...          1      1   0
4              1          1                   0  ...          1      0   0

   ya-books  ya-fantasy  ya-fiction  young-adult  young-adult-fiction  \
0         0           0           0            0                    0
1         0           0           0            0                    0
2         0           0           0            0                    0
3         0           0           0            0                    0
4         0           0           0            0                    0

   user_id  rating
0     2721     4.0
1    12509     3.0
2    30809     4.0
3    41007     5.0
4    44122     5.0

[5 rows x 184 columns]

C:\Users\RHEA TIWARI\.conda\lib\site-packages\pandas\core\reshape\merge.py:1219: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  warnings.warn(

In [23]:
combined_df

,book_id,4-stars,5-stars,abandoned,action,action-adventure,adult,adult-fiction,adventure,all-time-favorites,...,wish-list,women,ya,ya-books,ya-fantasy,ya-fiction,young-adult,young-adult-fiction,user_id,rating
0,105,0,0,0,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,2721,4.0
1,355,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,12509,3.0
2,415,0,0,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,30809,4.0
3,428,0,0,1,0,0,1,1,0,0,...,1,1,0,0,0,0,0,0,41007,5.0
4,449,0,0,1,0,0,0,1,1,0,...,1,0,0,0,0,0,0,0,44122,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13318,9998,0,0,1,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,48857,4.0
13319,9998,0,0,1,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,49462,3.0
13320,9998,0,0,1,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,50894,3.0
13321,9998,0,0,1,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,51295,5.0
13322,9998,0,0,1,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,51559,4.0

In [25]:
new_item

,book_id,4-stars,5-stars,abandoned,action,action-adventure,adult,adult-fiction,adventure,all-time-favorites,...,want-to-read,war,wish-list,women,ya,ya-books,ya-fantasy,ya-fiction,young-adult,young-adult-fiction
0,1,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
1,2,0,0,0,1,0,0,0,0,1,...,0,0,0,0,1,1,1,1,1,1
2,3,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
3,5,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
4,6,0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,31538647,1,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,1,0,1,0
9996,31845516,0,0,1,0,0,1,0,0,1,...,0,0,1,1,0,0,0,0,0,0
9997,32075671,0,1,0,0,0,0,0,0,1,...,0,0,1,0,1,1,0,1,1,1
9998,32848471,1,0,0,0,0,1,1,0,1,...,0,0,1,0,0,0,0,0,0,0
9999,33288638,1,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [34]:
import tensorflow as tf

# Number of features in your user and item data
num_user_features = 2  # Adjust this based on your input size
num_item_features = 182  # Adjust this based on your input size

# User model
user_NN = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(32)
])

# Item model
item_NN = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(32)
])

# Create the user input and pass it through the user network
input_user = tf.keras.layers.Input(shape=(num_user_features,))
vu = user_NN(input_user)
vu = tf.linalg.l2_normalize(vu, axis=1)

# Create the item input and pass it through the item network
input_item = tf.keras.layers.Input(shape=(num_item_features,))
vm = item_NN(input_item)
vm = tf.linalg.l2_normalize(vm, axis=1)

# Measure the similarity between user and item using dot product
output = tf.keras.layers.Dot(axes=1)([vu, vm])

# Define the model with user and item inputs, and similarity output
model = tf.keras.Model([input_user, input_item], output)

# Compile the model with Mean Squared Error as the loss function
model.compile(optimizer='adam', loss=tf.keras.losses.MeanSquaredError())

# Model summary
model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_7 (InputLayer)        [(None, 2)]                  0         []

 input_8 (InputLayer)        [(None, 182)]                0         []

 sequential_6 (Sequential)   (None, 32)                   37792     ['input_7[0][0]']

 sequential_7 (Sequential)   (None, 32)                   83872     ['input_8[0][0]']

 tf.math.l2_normalize_6 (TF  (None, 32)                   0         ['sequential_6[0][0]']
 OpLambda)

 tf.math.l2_normalize_7 (TF  (None, 32)                   0         ['sequential_7[0][0]']
 OpLambda)

 dot_3 (Dot)                 (None, 1)                    0         ['tf.math.l2_normalize_6[0][0]
                                                                    ',
                                                                     'tf.math.l2_normalize_7[0][0]
                                                                    ']

==================================================================================================
Total params: 121664 (475.25 KB)
Trainable params: 121664 (475.25 KB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________

In [35]:
cost_fn = tf.keras.losses.MeanSquaredError()

In [43]:
import numpy as np

# Assuming combined_df is your DataFrame containing user and item features
# Extract features for users and items
user_features = combined_df[['user_id', 'rating']].values  # Include relevant user features
item_features = combined_df.drop(columns=['user_id', 'rating']).values  # Drop non-feature columns

# Convert to TensorFlow tensors if needed
user_features_tf = tf.convert_to_tensor(user_features, dtype=tf.float32)
item_features_tf = tf.convert_to_tensor(item_features, dtype=tf.float32)

# Split into training and test sets (e.g., 80-20 split)
train_size = int(0.8 * len(combined_df))
X_user_train, X_user_test = user_features_tf[:train_size], user_features_tf[train_size:]
X_item_train, X_item_test = item_features_tf[:train_size], item_features_tf[train_size:]

In [45]:
# Assuming combined_df contains the 'rating' column
ratings = combined_df['rating'].values  # Target values (ratings)

# Convert to TensorFlow tensor if needed
ratings_tf = tf.convert_to_tensor(ratings, dtype=tf.float32)

# Split the target values (ratings) into training and test sets
y_train, y_test = ratings_tf[:train_size], ratings_tf[train_size:]

# Train the model with input features and target values (ratings)
history = model.fit(
    [X_user_train, X_item_train],  # Input features: user and item
    y_train,  # Target values: ratings
    epochs=50,  # Adjust based on your needs
    batch_size=32,  # Adjust based on your dataset size
    validation_split=0.2,  # Use part of the training data for validation
    verbose=1
)

Epoch 1/50
267/267 [==============================] - 2s 7ms/step - loss: 113.4324 - val_loss: 58.3739
Epoch 2/50
267/267 [==============================] - 2s 7ms/step - loss: 115.5794 - val_loss: 1105.5436
Epoch 3/50
267/267 [==============================] - 2s 6ms/step - loss: 245.0912 - val_loss: 48.9351
Epoch 4/50
267/267 [==============================] - 2s 6ms/step - loss: 778.1221 - val_loss: 54.9930
Epoch 5/50
267/267 [==============================] - 2s 6ms/step - loss: 3083.0581 - val_loss: 100.4933
Epoch 6/50
267/267 [==============================] - 2s 7ms/step - loss: 81.7508 - val_loss: 396.9475
Epoch 7/50
267/267 [==============================] - 1s 6ms/step - loss: 240.7585 - val_loss: 228.5680
Epoch 8/50
267/267 [==============================] - 2s 6ms/step - loss: 329.4866 - val_loss: 29.5435
Epoch 9/50
267/267 [==============================] - 2s 6ms/step - loss: 40178561024.0000 - val_loss: 21871.1367
Epoch 10/50
267/267 [==============================] - 2s 6ms/step - loss: 2308702.7500 - val_loss: 23287.3184
Epoch 11/50
267/267 [==============================] - 2s 6ms/step - loss: 19592.8633 - val_loss: 22088.9004
Epoch 12/50
267/267 [==============================] - 2s 6ms/step - loss: 18713.7012 - val_loss: 21311.1211
Epoch 13/50
267/267 [==============================] - 2s 7ms/step - loss: 18325.2266 - val_loss: 19655.3516
Epoch 14/50
267/267 [==============================] - 2s 6ms/step - loss: 18294.6094 - val_loss: 19245.3730
Epoch 15/50
267/267 [==============================] - 2s 6ms/step - loss: 16994.3203 - val_loss: 18163.6641
Epoch 16/50
267/267 [==============================] - 2s 6ms/step - loss: 16963.5879 - val_loss: 19035.2090
Epoch 17/50
267/267 [==============================] - 2s 6ms/step - loss: 17515.2168 - val_loss: 19401.6484
Epoch 18/50
267/267 [==============================] - 2s 7ms/step - loss: 15266.7734 - val_loss: 18319.2988
Epoch 19/50
267/267 [==============================] - 2s 7ms/step - loss: 15836.9824 - val_loss: 15202.6543
Epoch 20/50
267/267 [==============================] - 2s 7ms/step - loss: 14341.8584 - val_loss: 14406.9912
Epoch 21/50
267/267 [==============================] - 2s 7ms/step - loss: 14392.2324 - val_loss: 32745.1406
Epoch 22/50
267/267 [==============================] - 2s 7ms/step - loss: 124793.3750 - val_loss: 16477.6895
Epoch 23/50
267/267 [==============================] - 2s 7ms/step - loss: 13727.0742 - val_loss: 15773.6602
Epoch 24/50
267/267 [==============================] - 2s 7ms/step - loss: 13468.3096 - val_loss: 12078.0977
Epoch 25/50
267/267 [==============================] - 2s 7ms/step - loss: 12832.0840 - val_loss: 33746.1875
Epoch 26/50
267/267 [==============================] - 2s 7ms/step - loss: 11902.9453 - val_loss: 14621.2588
Epoch 27/50
267/267 [==============================] - 2s 6ms/step - loss: 13394.9043 - val_loss: 27085.7832
Epoch 28/50
267/267 [==============================] - 2s 6ms/step - loss: 14434.3379 - val_loss: 9161.8584
Epoch 29/50
267/267 [==============================] - 2s 6ms/step - loss: 14812.3037 - val_loss: 177904.5312
Epoch 30/50
267/267 [==============================] - 2s 6ms/step - loss: 11477.6973 - val_loss: 17828.9863
Epoch 31/50
267/267 [==============================] - 2s 7ms/step - loss: 17179.3496 - val_loss: 8008.6904
Epoch 32/50
267/267 [==============================] - 2s 6ms/step - loss: 30285.6133 - val_loss: 7842.6699
Epoch 33/50
267/267 [==============================] - 2s 6ms/step - loss: 71353.7812 - val_loss: 181398.9375
Epoch 34/50
267/267 [==============================] - 2s 6ms/step - loss: 23885.0566 - val_loss: 12147.8154
Epoch 35/50
267/267 [==============================] - 2s 6ms/step - loss: 83386.6953 - val_loss: 18451.9062
Epoch 36/50
267/267 [==============================] - 2s 7ms/step - loss: 1582737.0000 - val_loss: 744884.1875
Epoch 37/50
267/267 [==============================] - 2s 7ms/step - loss: 2628225.0000 - val_loss: 66195.1797
Epoch 38/50
267/267 [==============================] - 2s 7ms/step - loss: 12633.1045 - val_loss: 11997.6113
Epoch 39/50
267/267 [==============================] - 2s 7ms/step - loss: 27369.1777 - val_loss: 4598.3145
Epoch 40/50
267/267 [==============================] - 2s 7ms/step - loss: 46111.7188 - val_loss: 654076.2500
Epoch 41/50
267/267 [==============================] - 2s 7ms/step - loss: 2246363.5000 - val_loss: 73761.6328
Epoch 42/50
267/267 [==============================] - 2s 7ms/step - loss: 349285.1250 - val_loss: 284062.6875
Epoch 43/50
267/267 [==============================] - 2s 7ms/step - loss: 55947.6211 - val_loss: 19165.3477
Epoch 44/50
267/267 [==============================] - 2s 7ms/step - loss: 353544.4375 - val_loss: 2247304.5000
Epoch 45/50
267/267 [==============================] - 2s 6ms/step - loss: 596201.8125 - val_loss: 44391.7617
Epoch 46/50
267/267 [==============================] - 2s 7ms/step - loss: 14895.1553 - val_loss: 2446.8572
Epoch 47/50
267/267 [==============================] - 2s 7ms/step - loss: 316189.5938 - val_loss: 1343443.8750
Epoch 48/50
267/267 [==============================] - 2s 6ms/step - loss: 1349039.2500 - val_loss: 1009.4891
Epoch 49/50
267/267 [==============================] - 2s 7ms/step - loss: 563.0928 - val_loss: 1933.1799
Epoch 50/50
267/267 [==============================] - 2s 7ms/step - loss: 449.4643 - val_loss: 1318.4197

In [67]:
from sklearn.preprocessing import StandardScaler

# Normalize user and item features
scaler_user = StandardScaler()
user_features_scaled = scaler_user.fit_transform(X_user_train)  # Apply to training data

scaler_item = StandardScaler()
item_features_scaled = scaler_item.fit_transform(X_item_train)  # Apply to training data

# Later, use the scaled user and item features in your model
history = model.fit(
    [(user_features_scaled, item_features_scaled)],  # Input features: user and item
    y_train,  # Target values: ratings
    epochs=100,  # Adjust based on your needs
    batch_size=32,  # Adjust based on your dataset size
    validation_split=0.2,  # Use part of the training data for validation
    verbose=1
)

Epoch 1/100
267/267 [==============================] - 2s 8ms/step - loss: 0.0015 - val_loss: 0.0661
Epoch 2/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0018 - val_loss: 0.0642
Epoch 3/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0023 - val_loss: 0.0687
Epoch 4/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0025 - val_loss: 0.0693
Epoch 5/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0019 - val_loss: 0.0728
Epoch 6/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0016 - val_loss: 0.0613
Epoch 7/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0019 - val_loss: 0.0664
Epoch 8/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0019 - val_loss: 0.0685
Epoch 9/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0016 - val_loss: 0.0725
Epoch 10/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0029 - val_loss: 0.0671
Epoch 11/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0010 - val_loss: 0.0652
Epoch 12/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0011 - val_loss: 0.0679
Epoch 13/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0034 - val_loss: 0.0638
Epoch 14/100
267/267 [==============================] - 2s 6ms/step - loss: 6.6277e-04 - val_loss: 0.0667
Epoch 15/100
267/267 [==============================] - 2s 7ms/step - loss: 5.7278e-04 - val_loss: 0.0700
Epoch 16/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0018 - val_loss: 0.0644
Epoch 17/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0034 - val_loss: 0.0683
Epoch 18/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0017 - val_loss: 0.0685
Epoch 19/100
267/267 [==============================] - 2s 7ms/step - loss: 6.1726e-04 - val_loss: 0.0642
Epoch 20/100
267/267 [==============================] - 2s 7ms/step - loss: 7.5711e-04 - val_loss: 0.0688
Epoch 21/100
267/267 [==============================] - 2s 7ms/step - loss: 7.3625e-04 - val_loss: 0.0686
Epoch 22/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0011 - val_loss: 0.0674
Epoch 23/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0039 - val_loss: 0.0880
Epoch 24/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0011 - val_loss: 0.0707
Epoch 25/100
267/267 [==============================] - 2s 7ms/step - loss: 6.0832e-04 - val_loss: 0.0711
Epoch 26/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0015 - val_loss: 0.0712
Epoch 27/100
267/267 [==============================] - 2s 7ms/step - loss: 8.6158e-04 - val_loss: 0.0733
Epoch 28/100
267/267 [==============================] - 2s 7ms/step - loss: 9.0860e-04 - val_loss: 0.0747
Epoch 29/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0018 - val_loss: 0.0708
Epoch 30/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0019 - val_loss: 0.0759
Epoch 31/100
267/267 [==============================] - 2s 8ms/step - loss: 6.3863e-04 - val_loss: 0.0723
Epoch 32/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0017 - val_loss: 0.0725
Epoch 33/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0013 - val_loss: 0.0742
Epoch 34/100
267/267 [==============================] - 2s 7ms/step - loss: 9.6752e-04 - val_loss: 0.0794
Epoch 35/100
267/267 [==============================] - 2s 7ms/step - loss: 6.0702e-04 - val_loss: 0.0732
Epoch 36/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0012 - val_loss: 0.0740
Epoch 37/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0022 - val_loss: 0.0730
Epoch 38/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0026 - val_loss: 0.0746
Epoch 39/100
267/267 [==============================] - 2s 7ms/step - loss: 3.9412e-04 - val_loss: 0.0731
Epoch 40/100
267/267 [==============================] - 2s 7ms/step - loss: 2.7245e-04 - val_loss: 0.0716
Epoch 41/100
267/267 [==============================] - 2s 7ms/step - loss: 6.3361e-04 - val_loss: 0.0810
Epoch 42/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0012 - val_loss: 0.0753
Epoch 43/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0015 - val_loss: 0.0863
Epoch 44/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0019 - val_loss: 0.0795
Epoch 45/100
267/267 [==============================] - 2s 7ms/step - loss: 8.5255e-04 - val_loss: 0.0712
Epoch 46/100
267/267 [==============================] - 2s 7ms/step - loss: 7.8827e-04 - val_loss: 0.0751
Epoch 47/100
267/267 [==============================] - 2s 8ms/step - loss: 0.0021 - val_loss: 0.0771
Epoch 48/100
267/267 [==============================] - 2s 6ms/step - loss: 6.1548e-04 - val_loss: 0.0761
Epoch 49/100
267/267 [==============================] - 2s 7ms/step - loss: 9.0043e-04 - val_loss: 0.0789
Epoch 50/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0017 - val_loss: 0.0794
Epoch 51/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0023 - val_loss: 0.0744
Epoch 52/100
267/267 [==============================] - 2s 7ms/step - loss: 7.7442e-04 - val_loss: 0.0736
Epoch 53/100
267/267 [==============================] - 2s 7ms/step - loss: 2.9796e-04 - val_loss: 0.0753
Epoch 54/100
267/267 [==============================] - 2s 6ms/step - loss: 6.9642e-04 - val_loss: 0.0789
Epoch 55/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0030 - val_loss: 0.0776
Epoch 56/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0018 - val_loss: 0.0728
Epoch 57/100
267/267 [==============================] - 2s 6ms/step - loss: 6.6931e-04 - val_loss: 0.0762
Epoch 58/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0010 - val_loss: 0.0797
Epoch 59/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0019 - val_loss: 0.0777
Epoch 60/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0016 - val_loss: 0.0759
Epoch 61/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0027 - val_loss: 0.0835
Epoch 62/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0026 - val_loss: 0.0753
Epoch 63/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0022 - val_loss: 0.0748
Epoch 64/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0024 - val_loss: 0.0754
Epoch 65/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0017 - val_loss: 0.0742
Epoch 66/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0013 - val_loss: 0.0772
Epoch 67/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0024 - val_loss: 0.0899
Epoch 68/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0018 - val_loss: 0.0764
Epoch 69/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0035 - val_loss: 0.1370
Epoch 70/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0022 - val_loss: 0.1043
Epoch 71/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0019 - val_loss: 0.1185
Epoch 72/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0051 - val_loss: 0.1069
Epoch 73/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0020 - val_loss: 0.1299
Epoch 74/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0016 - val_loss: 0.0981
Epoch 75/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0098 - val_loss: 0.1242
Epoch 76/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0018 - val_loss: 0.1397
Epoch 77/100
267/267 [==============================] - 2s 7ms/step - loss: 5.2349e-04 - val_loss: 0.1384
Epoch 78/100
267/267 [==============================] - 2s 7ms/step - loss: 5.2920e-04 - val_loss: 0.1390
Epoch 79/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0024 - val_loss: 0.1574
Epoch 80/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0073 - val_loss: 0.2399
Epoch 81/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0036 - val_loss: 0.1988
Epoch 82/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0011 - val_loss: 0.1861
Epoch 83/100
267/267 [==============================] - 2s 6ms/step - loss: 4.4927e-04 - val_loss: 0.1870
Epoch 84/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0055 - val_loss: 0.1870
Epoch 85/100
267/267 [==============================] - 2s 8ms/step - loss: 0.0065 - val_loss: 0.2491
Epoch 86/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0033 - val_loss: 0.1864
Epoch 87/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0024 - val_loss: 0.2277
Epoch 88/100
267/267 [==============================] - 2s 6ms/step - loss: 7.1662e-04 - val_loss: 0.2375
Epoch 89/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0010 - val_loss: 0.2601
Epoch 90/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0046 - val_loss: 0.2950
Epoch 91/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0060 - val_loss: 0.3036
Epoch 92/100
267/267 [==============================] - 2s 6ms/step - loss: 5.6696e-04 - val_loss: 0.2454
Epoch 93/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0012 - val_loss: 0.2335
Epoch 94/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0012 - val_loss: 0.3328
Epoch 95/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0049 - val_loss: 0.1899
Epoch 96/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0032 - val_loss: 0.3956
Epoch 97/100
267/267 [==============================] - 2s 6ms/step - loss: 5.2975e-04 - val_loss: 0.2969
Epoch 98/100
267/267 [==============================] - 2s 7ms/step - loss: 0.0011 - val_loss: 0.2926
Epoch 99/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0021 - val_loss: 0.2538
Epoch 100/100
267/267 [==============================] - 2s 6ms/step - loss: 0.0023 - val_loss: 0.3540

In [54]:

user_features_scaled_test = scaler_user.transform(X_user_test)
item_features_scaled_test = scaler_item.transform(X_item_test)
# Reshape y_test to a 2D array before scaling


# Now you can use these scaled test features for predictions
loss = model.evaluate([user_features_scaled_test, item_features_scaled_test], y_test, verbose=1)
print(f"Test Loss: {loss}")

84/84 [==============================] - 0s 3ms/step - loss: 0.0871
Test Loss: 0.08713719993829727

In [56]:
# Use a list to pass both user and item features
predictions = model.predict([user_features_scaled_test, item_features_scaled_test])

84/84 [==============================] - 1s 5ms/step

In [59]:
# Use a separate scaler for ratings if needed
# Convert the TensorFlow tensor to a NumPy array before reshaping
y_train_np = y_train.numpy()

# Now reshape the NumPy array
y_train_scaled = scaler_ratings.fit_transform(y_train_np.reshape(-1, 1))

# Continue training your model with y_train_scaled

scaler_ratings = StandardScaler()
y_train_scaled = scaler_ratings.fit_transform(y_train_np.reshape(-1, 1))

# Train your model with y_train_scaled

# After making predictions, inverse-transform the ratings
predictions_inv = scaler_ratings.inverse_transform(predictions)

# Now compare with the actual y_test
mse = mean_squared_error(y_test, predictions_inv)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 13.373992919921875

In [65]:
import numpy as np
from sklearn.metrics import accuracy_score

# Inverse-transform the predictions if they were scaled
predictions_inv = scaler_ratings.inverse_transform(predictions)

# Convert y_test from EagerTensor to NumPy array and reshape
y_test_inv = scaler_ratings.inverse_transform(y_test.numpy().reshape(-1, 1))  # Inverse transform actual test values

# Round predictions to get predicted ratings
predicted_ratings = np.round(predictions_inv).astype(int)  # Convert to integers

# Ensure that y_test_inv is also in the same format
y_test_inv = y_test_inv.flatten().astype(int)

# Calculate accuracy using scikit-learn's accuracy_score
accuracy = accuracy_score(y_test_inv, predicted_ratings.flatten()) * 100

print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 28.52%

In [44]:
# Train the model
history = model.fit(
    [X_user_train, X_item_train],
    epochs=50,  # Adjust based on your needs
    batch_size=32,  # Adjust based on your dataset size
    validation_split=0.2,  # Use part of the training data for validation
    verbose=1
)

Epoch 1/50

ValueError: in user code:

    File "C:\Users\RHEA TIWARI\.conda\lib\site-packages\keras\src\engine\training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\RHEA TIWARI\.conda\lib\site-packages\keras\src\engine\training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\RHEA TIWARI\.conda\lib\site-packages\keras\src\engine\training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\RHEA TIWARI\.conda\lib\site-packages\keras\src\engine\training.py", line 1152, in train_step
        self._validate_target_and_loss(y, loss)
    File "C:\Users\RHEA TIWARI\.conda\lib\site-packages\keras\src\engine\training.py", line 1106, in _validate_target_and_loss
        raise ValueError(

    ValueError: Target data is missing. Your model was compiled with loss=mean_squared_error, and therefore expects target data to be provided in `fit()`.

In [32]:
user_features

array([[2.7210e+03, 4.0000e+00],
       [1.2509e+04, 3.0000e+00],
       [3.0809e+04, 4.0000e+00],
       ...,
       [5.0894e+04, 3.0000e+00],
       [5.1295e+04, 5.0000e+00],
       [5.1559e+04, 4.0000e+00]])

In [41]:
  # Include relevant user featuimport tensorflow as tf
import numpy as np

 # item features

# Convert to TensorFlow tensors
X_user_train = tf.convert_to_tensor(user_features, dtype=tf.float32)
X_item_train = tf.convert_to_tensor(item_features, dtype=tf.float32)

# Define the model
input_user = tf.keras.layers.Input(shape=(2,))  # User input shape
input_item = tf.keras.layers.Input(shape=(182,))  # Item input shape

# Define user neural network
user_NN = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(32)
])(input_user)

# Define item neural network
item_NN = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(32)
])(input_item)

# Measure the similarity of the two vector outputs
output = tf.keras.layers.Dot(axes=1)([user_NN, item_NN])

# Define the model
model = tf.keras.models.Model(inputs=[input_user, input_item], outputs=output)
model.compile(optimizer='adam', loss='mean_squared_error')  # Adjust loss function as needed

# Print model summary to confirm input shapes
model.summary()

# Train the model
# Note: Ensure you have target values (y) for your training, here using dummy values
y_train = np.random.rand(X_user_train.shape[0])  # Replace with actual target variable

history = model.fit(
    [X_user_train, X_item_train],
    y_train,
    epochs=50,  
    batch_size=32,  
    validation_split=0.2,
    verbose=1
)

Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_9 (InputLayer)        [(None, 2)]                  0         []

 input_10 (InputLayer)       [(None, 182)]                0         []

 sequential_8 (Sequential)   (None, 32)                   37792     ['input_9[0][0]']

 sequential_9 (Sequential)   (None, 32)                   83872     ['input_10[0][0]']

 dot_4 (Dot)                 (None, 1)                    0         ['sequential_8[0][0]',
                                                                     'sequential_9[0][0]']

==================================================================================================
Total params: 121664 (475.25 KB)
Trainable params: 121664 (475.25 KB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________
Epoch 1/50
WARNING:tensorflow:From C:\Users\RHEA TIWARI\.conda\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

334/334 [==============================] - 5s 8ms/step - loss: 245243412480.0000 - val_loss: 3787152.0000
Epoch 2/50
334/334 [==============================] - 2s 6ms/step - loss: 513887.4062 - val_loss: 285373.9062
Epoch 3/50
334/334 [==============================] - 2s 6ms/step - loss: 551348.4375 - val_loss: 485950.6250
Epoch 4/50
334/334 [==============================] - 2s 6ms/step - loss: 3139158.2500 - val_loss: 3940561.5000
Epoch 5/50
334/334 [==============================] - 2s 6ms/step - loss: 405351.1875 - val_loss: 530989.3125
Epoch 6/50
334/334 [==============================] - 2s 6ms/step - loss: 317557.1562 - val_loss: 152806.1562
Epoch 7/50
334/334 [==============================] - 2s 7ms/step - loss: 288354.4062 - val_loss: 897859.3125
Epoch 8/50
334/334 [==============================] - 2s 6ms/step - loss: 289369.2188 - val_loss: 299043.4375
Epoch 9/50
334/334 [==============================] - 2s 7ms/step - loss: 344059.5625 - val_loss: 239199.1406
Epoch 10/50
334/334 [==============================] - 2s 6ms/step - loss: 184810.3125 - val_loss: 942496.6250
Epoch 11/50
334/334 [==============================] - 2s 6ms/step - loss: 3321889.5000 - val_loss: 685120.5625
Epoch 12/50
334/334 [==============================] - 2s 6ms/step - loss: 509842.5312 - val_loss: 5138506.5000
Epoch 13/50
334/334 [==============================] - 2s 7ms/step - loss: 1173614.6250 - val_loss: 405612.9375
Epoch 14/50
334/334 [==============================] - 2s 7ms/step - loss: 109792352.0000 - val_loss: 125098696.0000
Epoch 15/50
334/334 [==============================] - 2s 7ms/step - loss: 4741872.5000 - val_loss: 1010256.8750
Epoch 16/50
334/334 [==============================] - 2s 7ms/step - loss: 5051076.5000 - val_loss: 1534414.3750
Epoch 17/50
334/334 [==============================] - 2s 6ms/step - loss: 1863347.0000 - val_loss: 368338592.0000
Epoch 18/50
334/334 [==============================] - 2s 7ms/step - loss: 59526616.0000 - val_loss: 98986736.0000
Epoch 19/50
334/334 [==============================] - 2s 6ms/step - loss: 7230605.0000 - val_loss: 6412340224.0000
Epoch 20/50
334/334 [==============================] - 2s 6ms/step - loss: 58176388.0000 - val_loss: 48893.9727
Epoch 21/50
334/334 [==============================] - 2s 6ms/step - loss: 86110.4453 - val_loss: 658565.5625
Epoch 22/50
334/334 [==============================] - 2s 7ms/step - loss: 145106.8906 - val_loss: 721552.1250
Epoch 23/50
334/334 [==============================] - 2s 6ms/step - loss: 24933458.0000 - val_loss: 2873684.7500
Epoch 24/50
334/334 [==============================] - 2s 6ms/step - loss: 149019.0469 - val_loss: 11943174.0000
Epoch 25/50
334/334 [==============================] - 2s 7ms/step - loss: 440279.1562 - val_loss: 21242674.0000
Epoch 26/50
334/334 [==============================] - 2s 7ms/step - loss: 20576198.0000 - val_loss: 95446.0547
Epoch 27/50
334/334 [==============================] - 2s 6ms/step - loss: 11211.9971 - val_loss: 118592.1406
Epoch 28/50
334/334 [==============================] - 2s 6ms/step - loss: 16471.3867 - val_loss: 40841.9922
Epoch 29/50
334/334 [==============================] - 2s 6ms/step - loss: 67636.2969 - val_loss: 42657.7266
Epoch 30/50
334/334 [==============================] - 2s 7ms/step - loss: 164760.1562 - val_loss: 23542.9824
Epoch 31/50
334/334 [==============================] - 2s 7ms/step - loss: 15111968.0000 - val_loss: 2930.3357
Epoch 32/50
334/334 [==============================] - 2s 7ms/step - loss: 2074.8274 - val_loss: 1711.0319
Epoch 33/50
334/334 [==============================] - 2s 7ms/step - loss: 1847.0270 - val_loss: 1648.5128
Epoch 34/50
334/334 [==============================] - 2s 6ms/step - loss: 1472.9463 - val_loss: 5785.3716
Epoch 35/50
334/334 [==============================] - 2s 7ms/step - loss: 1513.5349 - val_loss: 994.4387
Epoch 36/50
334/334 [==============================] - 2s 6ms/step - loss: 1513.8969 - val_loss: 7949.8062
Epoch 37/50
334/334 [==============================] - 2s 7ms/step - loss: 1199.9250 - val_loss: 5292.0801
Epoch 38/50
334/334 [==============================] - 2s 6ms/step - loss: 1232.0985 - val_loss: 917.4904
Epoch 39/50
334/334 [==============================] - 2s 7ms/step - loss: 1190.9507 - val_loss: 736.5220
Epoch 40/50
334/334 [==============================] - 2s 6ms/step - loss: 1549.4459 - val_loss: 35168.4414
Epoch 41/50
334/334 [==============================] - 2s 6ms/step - loss: 2239.6531 - val_loss: 1508.3219
Epoch 42/50
334/334 [==============================] - 2s 6ms/step - loss: 2077.4631 - val_loss: 12803.9355
Epoch 43/50
334/334 [==============================] - 2s 6ms/step - loss: 272060.6250 - val_loss: 107.6844
Epoch 44/50
334/334 [==============================] - 2s 6ms/step - loss: 116.4093 - val_loss: 143.5650
Epoch 45/50
334/334 [==============================] - 2s 6ms/step - loss: 92.6148 - val_loss: 67.0467
Epoch 46/50
334/334 [==============================] - 2s 6ms/step - loss: 86.5213 - val_loss: 67.2057
Epoch 47/50
334/334 [==============================] - 2s 6ms/step - loss: 90.3752 - val_loss: 329.9295
Epoch 48/50
334/334 [==============================] - 2s 6ms/step - loss: 72.7843 - val_loss: 452.2046
Epoch 49/50
334/334 [==============================] - 2s 6ms/step - loss: 115.8449 - val_loss: 58.3899
Epoch 50/50
334/334 [==============================] - 2s 6ms/step - loss: 84.1288 - val_loss: 71.6826

In [61]:
from sklearn.metrics import accuracy_score

# Inverse-transform the predictions if they were scaled
predictions_inv = scaler_ratings.inverse_transform(predictions)  # If y_train was scaled
y_test_inv = scaler_ratings.inverse_transform(y_test_np.reshape(-1, 1))  # Inverse transform actual test values

# Round predictions to get predicted ratings
predicted_ratings = np.round(predictions_inv)

# Calculate accuracy using scikit-learn's accuracy_score
accuracy = accuracy_score(y_test_inv.flatten(), predicted_ratings.flatten()) * 100

print(f"Accuracy: {accuracy:.2f}%")

NameError: name 'y_test_np' is not defined

In [66]:
# Example of thresholding
accuracy_with_threshold = np.mean(np.abs(y_test_inv - predicted_ratings.flatten()) <= 0.5) * 100
print(f"Accuracy (within 0.5 of actual): {accuracy_with_threshold:.2f}%")

Accuracy (within 0.5 of actual): 28.52%